### ISSUE TITLE
ts-repeat is a custom directive

### ISSUE THREAD

**Issue by hoetmaaiers** [mattiash/angular-tablesort#32]
My `ng-repeat` element is an attribute directive. Can it be that the table-sorting can't work? I get the following error:

```
Error: [$compile:ctreq] Controller 'browseContent', required by directive 'browseContentItem', can't be found!
http://errors.angularjs.org/1.4.3/$compile/ctreq?p0=browseContent&p1=browseContentItem
    at REGEX_STRING_REGEXP (http://localhost:3000/assets/javascripts/main.js:6298:779)
    at getControllers (http://localhost:3000/assets/javascripts/main.js:10120:255)
    at nodeLinkFn (http://localhost:3000/assets/javascripts/main.js:10137:162)
    at compositeLinkFn (http://localhost:3000/assets/javascripts/main.js:10035:964)
    at publicLinkFn (http://localhost:3000/assets/javascripts/main.js:10014:376)
    at link (http://localhost:3000/assets/javascripts/main.js:21093:45)
    at invokeLinkFn (http://localhost:3000/assets/javascripts/main.js:10223:317)
    at nodeLinkFn (http://localhost:3000/assets/javascripts/main.js:10137:70)
    at compositeLinkFn (http://localhost:3000/assets/javascripts/main.js:10035:964)
    at compositeLinkFn (http://localhost:3000/assets/javascripts/main.js:10035:1073) <tr browse-content-item="" ng-repeat="item in items" item="item" ng-class="{'odd': ng-class-odd, 'even': ng-class-even}" ts-repeat="">
```

**Comment by mattiash** [comment]
It seems like you have some sort of dependency problem, but it is impossible for me to tell without being able to run your code. Can you reproduce it in a plunkr?

**Comment by hoetmaaiers** [comment]
Hi @mattiash , I created my own sorting mixin. Next time I run into this issue, I'll try to recreate it in a Plunkr. Thanks for your response.
